carla:
  host: localhost
  port: 2000
  timeout: 10.0
  synchronous: true
  fixed_delta_seconds: 0.05
  weather: ClearSunset

camera:
  width: 1280
  height: 720
  fov: 70
  z: 60.0
  pitch: -90.0

run:
  duration: 20
  cam_index: 25

traffic:
  vehicles: 13
  walkers: 0

processing:
  process_interval: 2
  enable_static_detection: true

export:
  enable: true
  export_interval: 4
  export_start_frame: 30
  export_end_percent: 0.95
  max_exports: 100

