carla:
  host: localhost
  port: 2000
  timeout: 10.0
  synchronous: true
  fixed_delta_seconds: 0.05
  weather: ClearNoon

camera:
  width: 1280
  height: 720
  fov: 90
  z: 60.0
  pitch: -90.0

run:
  duration: 20
  cam_index: 50

traffic:
  vehicles: 10
  walkers: 3

processing:
  process_interval: 2
  enable_static_detection: false

export:
  enable: true
  export_interval: 10
  export_start_frame: 50
  export_end_percent: 0.95
  max_exports: 100

