name: conda-env
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - aom=3.3.0
  - bzip2=1.0.8
  - ca-certificates=2025.10.5
  - certifi=2024.8.30
  - ffmpeg=5.0.1
  - freetype=2.13.3
  - gmp=6.2.1
  - gnutls=3.6.13
  - icu=73.1
  - lame=3.100
  - ld_impl_linux-64=2.40
  - libdrm=2.4.124
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libiconv=1.17
  - libnsl=2.0.0
  - libpciaccess=0.18
  - libpng=1.6.39
  - libstdcxx-ng=11.2.0
  - libva=2.21.0
  - libvpx=1.11.0
  - libxcb=1.17.0
  - libxml2=2.13.8
  - libzlib=1.3.1
  - ncurses=6.5
  - nettle=3.6
  - openh264=2.1.1
  - openssl=3.0.3
  - pip=22.3.1
  - pthread-stubs=0.3
  - python=3.7.12
  - readline=8.3
  - setuptools=65.6.3
  - sqlite=3.50.2
  - svt-av1=1.1.0
  - tk=8.6.15
  - wheel=0.38.4
  - x264=1!161.3030
  - x265=3.5
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xorg-libxext=1.3.6
  - xorg-libxfixes=6.0.1
  - xorg-xorgproto=2024.1
  - xz=5.6.4
  - zlib=1.3.1
  - pip:
      - carla==0.9.15
      - drawio-diagram-generator==1.0.1
      - networkx==2.6.3
      - numpy==1.21.6
      - opencv-python==4.12.0.88
      - pillow==9.5.0
      - pygame==2.6.1
      - shapely==2.0.7
      - PyYAML==6.0
prefix: /home/akonst08/.conda/envs/conda-env
